### ISSUE TITLE
It is malfunctioning

### ISSUE THREAD

**Issue by Faizan090** [salmansheri/taskify#3]
<img width="653" alt="Screenshot 2024-02-14 183641" src="https://github.com/salmansheri/taskify/assets/135043131/13dad93c-34f9-47d7-96c5-8045dd1bf3df">

**Comment by Faizan090** [comment]
Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.

**Comment by salmansheri** [comment]
Thank you Faizan for your contribution the error has been fixed
